# Generated by Django 4.1.1 on 2022-10-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
