# Generated by Django 4.1.1 on 2022-10-20 11:39

import django.core.validators
from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invitationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), users.validators.validate_size], verbose_name='user avatar'),
        ),
    ]
