# Generated by Django 4.1.1 on 2022-10-26 12:37

import communities.models
import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=communities.models.Community.file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg']), users.validators.validate_size], verbose_name='community logo'),
        ),
        migrations.AlterField(
            model_name='community',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
