# Generated by Django 4.1.1 on 2022-11-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_alter_community_logo_alter_community_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(choices=[(1, 'safety_status'), (2, 'master_off')], max_length=15, verbose_name='activity')),
                ('status', models.BooleanField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
