version: '3.0'
services:
  backend:
    image: $AWS_ECR_ID/$CIRCLE_BRANCH-$PROJECT_NAME:backend-$TAG
    ports:
      - "<application port>:<application port>"
    env_file:
      - ./.env
    #entrypoint: sh /<project_name>/deployment/init.sh
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/$CIRCLE_BRANCH-$PROJECT_NAME-backend
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: $CIRCLE_BRANCH-backend
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535