FROM python:3.10-slim

WORKDIR /amity-backend-t2

RUN set -eux && \
    apt-get update &&  \
    apt-get upgrade -y && \
    #apt-get install -y  \
    #rm -rf /var/lib/apt/lists/*
    apt-get install docker
    aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
    docker tag v1.0 aws_account_id.dkr.ecr.region.amazonaws.com/base-amity-t2:python:3.10-slim.v1.0
    docker push aws_account_id.dkr.ecr.region.amazonaws.com/base-amity-t2:python:3.10-slim.v1.0

