version: "3.0"

version: '3.0'
services:
  backend:
    image: $AWS_ECR_ID/$CIRCLE_BRANCH-$PROJECT_NAME:backend-$TAG
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    entrypoint: #sh /<project_name>/deployment/init.sh
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/$CIRCLE_BRANCH-$PROJECT_NAME-backend
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: $CIRCLE_BRANCH-backend
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535